### ISSUE TITLE
More errors :(

### ISSUE THREAD

**Issue by ghost** [billythegoat356/Specter#8]
Traceback (most recent call last):
  File "c:\Users\Xavier Dudley\Desktop\specter.py", line 232, in <module>
    main()
  File "c:\Users\Xavier Dudley\Desktop\specter.py", line 223, in main
    script = Specter.specterize(script=script)
  File "c:\Users\Xavier Dudley\Desktop\specter.py", line 64, in specterize
    script = Specter.layer_2(script=script)
  File "c:\Users\Xavier Dudley\Desktop\specter.py", line 148, in layer_2
    return dumps(compile(script, 'Specter', 'exec'))
SystemError: excessive stack use: stack is 3479 deep

**Comment by billythegoat356** [comment]
try again, idk why you have this error

**Comment by ghost** [comment]
So I tried doing it on a shorter python file and it worked (shorter meaning less lines) but where does it save the obfed file?

**Comment by billythegoat356** [comment]
it saves it in the current directory, you have to extract the zip file

**Comment by ghost** [comment]
> Traceback (most recent call last): File "c:\Users\Xavier Dudley\Desktop\specter.py", line 232, in main() File "c:\Users\Xavier Dudley\Desktop\specter.py", line 223, in main script = Specter.specterize(script=script) File "c:\Users\Xavier Dudley\Desktop\specter.py", line 64, in specterize script = Specter.layer_2(script=script) File "c:\Users\Xavier Dudley\Desktop\specter.py", line 148, in layer_2 return dumps(compile(script, 'Specter', 'exec')) SystemError: excessive stack use: stack is 3479 deep

any fix yet for this
